owner: ahmedabdelkhalek1
repo: drones-status

sites:
  - name: GCAA Drones Portal
    url: https://drones.gov.ae/
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: GCAA Grafana
    url: https://api.drones.gov.ae/grafana/login
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000

status-website:
  cname:    # Remove if no custom domain
  baseUrl: /drones-status              # If default GitHub domain, use this
  name: GCAA Drones Status
  introTitle: "GCAA Drones Portal Status"
  introMessage: "Automatic external status checks every 5 min."

notifications:
  email:
    to: ahabdelnabi@eand.com

workflowSchedule:
  uptime: "*/5 * * * *"
